- 머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반하므로 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 넘파이는 매우 중요
- 머신러닝 알고리즘이나 패키지를 직접 만드는 개발자가 아니라면 상세하게 알 필요는 없으나 넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요

In [1]:
# 넘파이의 기반 데이터 타입은 ndarray이며 이를 이용해 다차원 배열을 쉽게 만들 수 있다.
import numpy as np

In [4]:
array1 = np.array([1,2,[[3,5],[4,6]],
                  [3,4]])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(4,)


<ipython-input-4-af7980f245c4>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1 = np.array([1,2,[[3,5],[4,6]],


In [8]:
array1 = np.array([[1,2],
                   [1,3]])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(2, 2)


In [9]:
array1 = np.array([[1,2],
                   [1,3,5]])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(2,)


<ipython-input-9-e93a199cae2c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1 = np.array([[1,2],


In [10]:
array1

array([list([1, 2]), list([1, 3, 5])], dtype=object)

In [17]:
array1 = np.array([[2,3],[[1,2],[2,1]]])
print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(2, 2)


<ipython-input-17-44dde1eeb98d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array1 = np.array([[2,3],[[1,2],[2,1]]])


하나의 ndarray객체에는 int와 float가 함께 있을 수 없다.

In [20]:
# ndarray의 데이터타입
array2 = np.array([1,2])
array2.dtype

dtype('int64')

In [21]:
# ndarray의 데이터타입
array2 = np.array([[1,2],[3,3.4]])
array2.dtype

dtype('float64')

In [23]:
array3 = np.array([1,2])
array3 = array3.astype('float64')
array3.dtype

dtype('float64')

In [25]:
array2 = array2.astype('int64')
array2

array([[1, 2],
       [3, 3]])

In [38]:
np.arange(10,-10,-2)

array([10,  8,  6,  4,  2,  0, -2, -4, -6, -8])

In [40]:
np.zeros((3,2), dtype='int32')

In [43]:
array_z = np.zeros((3,2), dtype='int32')
array_z.reshape(2,3)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [49]:
# -1을 넣으면 알아서 호환되는 인자를 선택하여 적용
array_z.reshape(-1,3)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [50]:
a = np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [53]:
a1 = a.reshape((-1,1))

In [56]:
a1.shape

(8, 1)

In [58]:
np.arange(8).shape

(8,)

In [60]:
np.arange(8).reshape(-1,1).shape

(8, 1)

In [66]:
a = np.zeros((2,2,2))
a[1,1,1]=10
a

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0., 10.]]])

In [70]:
a[1,0:2]

array([[ 0.,  0.],
       [ 0., 10.]])

In [72]:
a = np.arange(16).reshape((4,4))
a[2]

array([ 8,  9, 10, 11])

In [74]:
# 팬시 인덱싱 : 리스트나 집합이 인덱스 안에 들어감
print(a)
print(a[[1,3],2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 6 14]


In [75]:
# 불린 인덱싱 : 조건을 넣어 True와 False가 들어감
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [76]:
# 행렬 정렬
org_array = np.array([3,1,9,5])
np.sort(org_array)

array([1, 3, 5, 9])

In [81]:
a = np.arange(15,-1,-1).reshape(4,4)
print(a)
print()
print(np.sort(a))
print()
print(np.sort(a, axis=0))
print()
print(np.sort(a, axis=1))

[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


numpy에서 axis의 경우 pandas와는 반대다.

In [83]:
# 행렬정렬 시에 원본 행렬의 인덱스를 반환해 주는 메소드인데 행렬 정렬은 진행하기 전에 적용하여 정렬을 진행했다는 가정하에 인덱스를 추출
print(org_array)
np.argsort(org_array)

[3 1 9 5]


array([1, 0, 3, 2])

In [84]:
# 행렬 내림차순 정렬 시 원본 행렬 인덱스
np.argsort(org_array)[::-1]

array([2, 3, 0, 1])

In [85]:
# 행렬 내적(곱)
a = np.arange(1,7).reshape(2,3)
b = np.arange(7,13).reshape(3,2)
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [86]:
# 전치행렬
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])