# numpy
- c언어로 구현된 파이썬 라이브러리
- 고성능 수치계산을 위해 제작
- numerical python
- 벡터 및 행렬 연산에 매우 편리한 기능 제공
- pandas와 matplotlib과 더불어 데이터 분석에 필수 라이브러리
- 기본적으로 array 단위로 데이터 처리
- 대표적인 자료형 : ndarray 객체

## numpt 

In [1]:
import numpy as np

## Array 정의 및 사용

In [2]:
# python의 리스트 이용
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [3]:
b = [1,2,3,4,5]
b

[1, 2, 3, 4, 5]

In [4]:
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [6]:
# array 형태 확인
arr1.shape

(5,)

In [7]:
# array 자료형 확인
arr1.dtype

dtype('int32')

## 배열 생성 : numpy가 제공하는 함수를 이용한 단순배열
- zeros, ones
- zeros_like , ones_like
- empty
- arange
- linespace, logspace

In [9]:
# 0인 배열을 생성 : zeros(배열크기) 
a = np.zeros(3)
a

array([0., 0., 0.])

In [10]:
b = np.zeros(5,dtype="i")
b

array([0, 0, 0, 0, 0], dtype=int32)

- numpy 자료형, dtype의 접두사
- "i" :정수형
- "u" : uint => 부호가없는 정수
- "f" : float
- "b" : 논리형 True/False
- "c" : complex
- "s" : 문자열(string)


In [11]:
x = np.array([1,2,3],dtype='f')
x.dtype

dtype('float32')

In [12]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
c = np.zeros((5,2),dtype='i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [14]:
e = np.ones((2,3,4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
# 기존의 배열의 크기를 그대로 사용하여 배열 생성
## zeros_like
## ones_like

In [16]:
f = np.ones_like(b)
f

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
g = np.empty((4,3))
g

array([[1.03050673e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 3.11523242e-307, 3.11542374e+179],
       [1.20134165e-075, 1.32394743e-071, 7.25060504e-042],
       [3.26769887e-032, 1.57144822e-076, 1.25877869e-075]])

In [18]:
# range() : 순차리스트, 수열 생성
# range(5) : 0,1,2,3,4
# range(1,10) : 1~9
# arange() : Numpy 버전의 range
np.arange(10) # 0~9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [24]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치행렬
- 행과 열을 바꾸는 기능
- T

In [25]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 배열의 크기 변형
- 배열의 크기 속성 : shape 배열명.속성
- 배열의 크기 변경 : reshape

In [28]:
a = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a.shape

(12,)

In [31]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a.reshape(2,2,-1) #행이나 열값무시 -붙임

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [35]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [37]:
# 다차원 배열을 1차원 배열로 생성하는 flatten, ravel 메서드
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a = a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [42]:
x.shape

(5,)

In [43]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [44]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [45]:
# 차원만 증가시키는 newaxis 
x

array([0, 1, 2, 3, 4])

In [48]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# numpy 배열의 연산

In [49]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [51]:
%%time
res = np.zeros_like(x)
for i in range(10000):
    res[i] = x[i] + y[i]

CPU times: total: 15.6 ms
Wall time: 3.07 ms


In [52]:
res[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [53]:
%%time
z = x + y

CPU times: total: 0 ns
Wall time: 9.51 ms


In [54]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [55]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,3])

In [57]:
a == b

array([False,  True, False, False])

In [58]:
a >= b

array([False,  True,  True,  True])

In [59]:
np.all(a == b)

False

In [60]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [61]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [62]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [63]:
np.log(a+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [64]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [66]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 브로드캐스팅
- 서로 크기가 다른 배열의 사칙연산을 수행하는 기능
- 크기가 작은 배열이 자동적으로 크기가 큰 배열의 크기로 맞춰지는 기능

In [67]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [68]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [69]:
x + y

array([1, 2, 3, 4, 5])

In [70]:
y = np.arange(12).reshape(3,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
y+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
z = np.ones_like(y)
z

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [73]:
y + z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 그룹함수 or 차원축소 연산
- 최대/최소 : min ,max ,argmin, argmax
- 기초통계 : sum, mean, median, std, var
- 논리연산 : all, any

In [74]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [75]:
np.sum(x)

10

In [76]:
x.sum()

10

In [77]:
x = np.array([1,3,2])
x

array([1, 3, 2])

In [78]:
np.min(x)

1

In [79]:
x.min()

1

In [81]:
x.argmin()

0

In [82]:
x.argmax()

1

In [83]:
x.mean()

2.0

In [84]:
np.mean(x)

2.0

In [85]:
np.median(x)

2.0

In [86]:
y = np.array([1,2,3,1])
y

array([1, 2, 3, 1])

In [88]:
np.median(y)

1.5

In [89]:
np.all([True,True,False])

False

In [90]:
np.any([True,True,False])

True

In [91]:
a = np.zeros((100,100),dtype='i')
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [92]:
np.any(a != 0)

False

In [93]:
np.all(a == a)

True

In [94]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,4])
c = np.array([6,4,4,5])

In [97]:
((a <= b) & (b <= c)).all()

True

- 축 : axis=0(열), axis=1(행), default(axis=0)

In [101]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [102]:
x.sum()

6

In [103]:
x.sum(axis=0)

array([3, 3])

In [104]:
x.sum(axis=1)

array([2, 4])

## 정렬(sort)
- 2차원 이상일 경우에는 행이나 열을 각각 따로 정렬
- axis = 0 각 열을 기준으로 정렬, 1이면 행을 기준으로 정렬
- 생략하면 axis = 0
- axis = -1가 주어지면 안쪽차원이 기준

In [112]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [107]:
np.sort(a) # axis=1은 axis=-1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [108]:
np.sort(a,axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [109]:
np.sort(a,axis=-1)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [111]:
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [113]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [115]:
# 정렬을 하지않고 순서만 알고 싶다면 argsort 명령어 사용
a = np.array([4,2,3,8])
b = np.argsort(a)
b

array([1, 2, 0, 3], dtype=int64)

In [117]:
a[b]

array([2, 3, 4, 8])

In [118]:
np.sort(a)

array([2, 3, 4, 8])

## Fancy Indexing : 펜시 인덱싱
- boolean 인덱싱을 이용하는 것
- 마스크 인덱싱
- 규칙이 일정하지 않지만 원하는 데이터를 추출하고자 할 때 사용한다

In [119]:
names = np.array(['park','park','kim','joan','lee','park','hong','park'])
names

array(['park', 'park', 'kim', 'joan', 'lee', 'park', 'hong', 'park'],
      dtype='<U4')

In [120]:
names.shape

(8,)

In [121]:
# 정규분포 : np.random.randn(), 평균은 0이고 표준편차는 1인 
# np.random.rand() : 0~1 사이의 난수 발생
data = np.random.randn(8,4)
data

array([[-0.49029003, -0.87045076, -0.8830325 , -0.65618555],
       [-0.70107794, -0.96066885, -0.86599088,  0.4428292 ],
       [ 1.06418335,  1.93743427, -1.87643794, -1.43245718],
       [ 0.71418077, -0.25033832, -0.83504411,  0.18922716],
       [ 1.32018859, -2.05789728,  1.19232722,  2.67485656],
       [-0.72854976, -1.02737062,  0.09479944,  2.46565138],
       [ 0.31036344, -2.54099334, -0.82656604,  0.22577559],
       [-0.76070107, -0.88270826, -0.58545037, -0.30198519]])

In [122]:
data.shape

(8, 4)

In [125]:
index = (names == 'park')
data[index,:]

array([[-0.49029003, -0.87045076, -0.8830325 , -0.65618555],
       [-0.70107794, -0.96066885, -0.86599088,  0.4428292 ],
       [-0.72854976, -1.02737062,  0.09479944,  2.46565138],
       [-0.76070107, -0.88270826, -0.58545037, -0.30198519]])

In [126]:
# 요소가 kim인 행의 데이터만 추출
data[names=='kim',:]

array([[ 1.06418335,  1.93743427, -1.87643794, -1.43245718]])

In [128]:
# kim과 hong
data[(names == 'kim') | (names =='hong'),:]

array([[ 1.06418335,  1.93743427, -1.87643794, -1.43245718],
       [ 0.31036344, -2.54099334, -0.82656604,  0.22577559]])

In [129]:
data

array([[-0.49029003, -0.87045076, -0.8830325 , -0.65618555],
       [-0.70107794, -0.96066885, -0.86599088,  0.4428292 ],
       [ 1.06418335,  1.93743427, -1.87643794, -1.43245718],
       [ 0.71418077, -0.25033832, -0.83504411,  0.18922716],
       [ 1.32018859, -2.05789728,  1.19232722,  2.67485656],
       [-0.72854976, -1.02737062,  0.09479944,  2.46565138],
       [ 0.31036344, -2.54099334, -0.82656604,  0.22577559],
       [-0.76070107, -0.88270826, -0.58545037, -0.30198519]])

In [131]:
# 0번째 열의 값이 0보다 작은 행을 추출
data[:,0]<0

array([ True,  True, False, False, False,  True, False,  True])

In [132]:
data[data[:,0]<0,:]

array([[-0.49029003, -0.87045076, -0.8830325 , -0.65618555],
       [-0.70107794, -0.96066885, -0.86599088,  0.4428292 ],
       [-0.72854976, -1.02737062,  0.09479944,  2.46565138],
       [-0.76070107, -0.88270826, -0.58545037, -0.30198519]])

In [136]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열의 값
data[data[:,0]<0,2:4]

array([[-0.8830325 , -0.65618555],
       [-0.86599088,  0.4428292 ],
       [ 0.09479944,  2.46565138],
       [-0.58545037, -0.30198519]])

In [137]:
# 0번째 열의 값이 0보다 작은 행의 2,3번째 열의값을 0으로 치환
data[data[:,0]<0,2:4] =0 
data

array([[-0.49029003, -0.87045076,  0.        ,  0.        ],
       [-0.70107794, -0.96066885,  0.        ,  0.        ],
       [ 1.06418335,  1.93743427, -1.87643794, -1.43245718],
       [ 0.71418077, -0.25033832, -0.83504411,  0.18922716],
       [ 1.32018859, -2.05789728,  1.19232722,  2.67485656],
       [-0.72854976, -1.02737062,  0.        ,  0.        ],
       [ 0.31036344, -2.54099334, -0.82656604,  0.22577559],
       [-0.76070107, -0.88270826,  0.        ,  0.        ]])

# 기술통계분석

In [138]:
x = np.array([18,5,10,23,19,-8,10,0,0,5,2,15,8,2,5,4,15,-1,4,-7,-24,7,9,-6,23,-13])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수 : len

In [139]:
len(x)

26

## 평균 : mean

In [140]:
np.mean(x)

4.8076923076923075

## 분산 :var

In [142]:
np.var(x)

115.23224852071006

In [145]:
# 비편향 분석
np.var(x,ddof=1)

119.84153846153846

## 표준편차 : std

In [146]:
np.std(x)

10.734628476137871

## 최대값과 최소값 : max, min

In [147]:
np.max(x)

23

In [148]:
np.min(x)

-24

## 중앙값 : median

In [150]:
np.median(x)

5.0

## 4분위수:quantile, percentile

In [155]:
np.percentile(x,0) # 최소값

-24.0

In [156]:
np.percentile(x,25) # 1사분위수

0.0

# 난수

## 시드설정 : 0과 같거나 큰 정수

In [157]:
np.random.seed(0)

In [158]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [159]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [160]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [161]:
np.random.seed(0)

In [162]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [163]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [166]:
arr1 = np.random.random((3,3)) # 0~1사이의 실수 균등분포
arr2 = np.random.normal(2,1,(3,2)) # 평균2, 편차1이 되는 정규분포 
arr3 = np.random.randn(2,3) # 표준 정규분포, 평균은 0이고 편차는 1
arr4 = np.random.randint(0,10,(2,2)) # 정수 


In [168]:
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[[0.36371077 0.57019677 0.43860151]
 [0.98837384 0.10204481 0.20887676]
 [0.16130952 0.65310833 0.2532916 ]]
[[0.38610215 1.78725972]
 [1.10453344 2.3869025 ]
 [1.48919486 0.81936782]]
[[-0.02818223  0.42833187  0.06651722]
 [ 0.3024719  -0.63432209 -0.36274117]]
[[7 2]
 [9 2]]


## 데이터 샘플링 , shuffle 명령과 같다
- np.choice(배열,size,replace,p)
- 배열 : arange(n)

In [171]:
np.random.choice(5,5,replace=False)

array([0, 4, 3, 2, 1])

In [172]:
np.random.choice(5,3,replace=False)

array([3, 4, 0])

In [173]:
np.random.choice(5,10)

array([3, 0, 3, 2, 3, 0, 0, 0, 3, 2])

In [180]:
np.random.choice(5,10,p=[0.1,0.5,0.3,0,0.1])

array([2, 2, 2, 2, 1, 4, 1, 2, 1, 2])

In [181]:
# 0에서 1사이의 균일분포
np.random.rand(10)

array([0.24979628, 0.31321833, 0.96541622, 0.58846509, 0.65966841,
       0.53320625, 0.23053302, 0.39486929, 0.61880856, 0.47486752])

In [182]:
np.random.rand(3,5)

array([[0.47013219, 0.71607453, 0.287991  , 0.38346223, 0.74916984],
       [0.87845219, 0.10286336, 0.09237389, 0.35404666, 0.55181626],
       [0.03362509, 0.96896177, 0.32099724, 0.22126269, 0.1412639 ]])

In [183]:
# np.random.randint(low,high=None,size)
np.random.randint(10,size=10)

array([6, 3, 6, 5, 7, 0, 8, 4, 6, 5])

In [184]:
np.random.randint(10,20,size=10)

array([18, 12, 13, 19, 17, 15, 13, 14, 15, 13])

In [185]:
np.random.randint(10,20,size=(3,5))

array([[13, 17, 19, 19, 19],
       [17, 13, 12, 13, 19],
       [17, 17, 15, 11, 12]])

## 정수 데이터 카운팅
- unique : 중복제거
- return_counts = True => 각 값의 개수

In [186]:
np.unique([11,11,11,23,43,23,43])

array([11, 23, 43])

In [188]:
a = np.array(['a','b','b','b','c','a'])
a

array(['a', 'b', 'b', 'b', 'c', 'a'], dtype='<U1')

In [189]:
np.unique(a)

array(['a', 'b', 'c'], dtype='<U1')

In [190]:
index,count = np.unique(a,return_counts=True)
print(index)
print(count)

['a' 'b' 'c']
[2 3 1]


# Data Analysis - 2nd

In [194]:
# zeros, ones, full(size,k), eye
a = np.full((2,3),5)
print(a)
# eye : 정방 행렬(행과 열의 개수가 같음)
b= np.eye(3)
print(b)

[[5 5 5]
 [5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [195]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [196]:
arr2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [198]:
arr2d[2][0]

7

In [199]:
arr2d[2,0]

7

In [200]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [201]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
a = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [203]:
b =a # b = a[:]
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [205]:
a[0,0] = 100
print(a)
print(b)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [206]:
# copy()
c = a.copy()
print(c)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [207]:
c[0,0]=1
print(c)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [208]:
arr # 2 x 3 x 3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [209]:
arr[0] 

array([[1, 2, 3],
       [4, 5, 6]])

In [210]:
arr1 = arr[0].copy()

In [215]:
arr[0][1]

array([4, 5, 6])

In [214]:
arr[0,1,:]

array([4, 5, 6])

In [216]:
arr = np.arange(15).reshape((3, -1))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [217]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])